package com.platform.analytics.report;

import java.time.Instant;
import java.util.List;
import java.util.Map;
import java.util.UUID;

/**
 * Snapshot of quality metrics for a release window.
 * Generated by {@link ReleaseReportService}.
 */
public record ReleaseReportDto(
        UUID projectId,
        String projectSlug,

        /** Release tag or label (e.g. "v2.4.0") — null if not specified. */
        String releaseTag,

        Instant from,
        Instant to,

        // Execution summary
        int totalRuns,
        int totalTests,
        int totalPassed,
        int totalFailed,
        int totalBroken,
        int totalSkipped,

        double overallPassRate,

        // Flakiness
        int flakyTestCount,
        int criticalFlakyCount,
        List<String> topCriticalFlakyTests,

        // AI failure category breakdown (only present if platform-ai is enabled)
        Map<String, Long> failuresByAiCategory,

        // Top failing tests (by failure count in window)
        List<TopFailingTest> topFailingTests,

        // Quality gate against the most recent run in the window
        boolean qualityGatePassed,
        List<String> qualityGateViolations,

        Instant generatedAt
) {
    public record TopFailingTest(String testId, int failureCount, double failureRate) {}
}
